version: '2'
services:
  db:
    image: mysql:5.5
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    container_name: "example_playframework_db_development"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: example_playframework_development
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root
    ports:
      - "9000:9000"
    links:
      - db
    environment:  
      RAILS_ENV: development
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    container_name: "example_playframework_development"